server:
  port: 8765


spring:
  application:
    name: APIGateWay
  cloud:
    gateway:
      routes:
        - id: Seminar_8
          uri: http://localhost:8081/
          predicates:
            - Path=/visitor/**



